### ISSUE TITLE
For what is the `TryInto<usize>` implementation needed?

### ISSUE THREAD

**Issue by tsdh** [vstojkovic/rt-format#2]
I wanted to be able to specify format strings in a config file and then use them at runtime.  Your crate enabled that I could define [this `format` function](https://git.sr.ht/~tsdh/swayr/tree/next/item/src/rtfmt.rs#L76) which is like a one-arg version of `format!` but where the format string is specified at runtime.  Thanks a lot!

I have to confess that parts of the implementation are a bit above my current rust foo.  Especially I don't quite understand why I had to implement `TryInto<usize>` for the type I use for positional arguments.  What is the intent behind it?

**Comment by oberien** [comment]
Formatting can include positional or named width specifiers (see the test-code below). For arguments to be used as width parameter of another format argument, passed values must be convertible to `usize`. Instead of implementing `TryInto<usize>`, you can also directly implement [`ConvertToSize`](https://docs.rs/rt-format/0.2.0/rt_format/parser/trait.ConvertToSize.html).

https://github.com/vstojkovic/rt-format/blob/02c02ef3efbf7020ce43908a3863d74232345409/tests/test_output.rs#L72-L89

**Comment by vstojkovic** [comment]
@oberien is correct, this is to provide support for providing width and precision in your positional/named arguments. I just wanted to add that I don't really like that I had to make that mandatory, but I haven't found a way to make it optionally supported depending on whether you implement the trait or not. I'm not a Rust expert, so maybe I'm missing something, but to me it looks like I have to make it mandatory until the trait specialization is stabilized.

**Comment by tsdh** [comment]
@oberien @vstojkovic Thank you both, that makes sense, obviously.  And now I'm also confident that I implemented it the right way, giving an `Err` each time, cause I only ever provide a `&str` as argument which won't work with `$`.

Once you know where it is needed, it all makes sense. :-)
